- name: DB setup
  hosts: DB
  become: yes
  vars:
   login_host : db.mohandevops.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no 
  tasks:
  - name: Installing mysql server
    ansible.builtin.dnf:
     name: mysql-server
     state: present

  - name: Start and enable the mysql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes
  
  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11
  
  # checking DB Password is setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
 
  - name: print output
    ansible.builtin.debug:
     msg: "Output : {{ my_sql_connection_output }}"
  
  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition